nodeLinker: node-modules
enableTelemetry: false
compressionLevel: mixed

packageExtensions:
  "@tensorflow/tfjs-data@*":
    peerDependencies:
      seedrandom: "*"
    peerDependenciesMeta:
      seedrandom:
        optional: true
