# Railway Service Configuration
# Forces correct root directories and Railpack builder

version: 1

services:
  - name: polytrade-fe
    builder: nixpacks
    plan:
      providers: ["nodejs"]
      build:
        install: "yarn install:all"
        command: "yarn build:frontend"
      start:
        command: "yarn start:frontend"

  - name: polytrade-be
    builder: nixpacks
    plan:
      providers: ["nodejs"]
      build:
        install: "yarn install:all"
        command: "yarn build:backend"
      start:
        command: "yarn start:backend"
    
  - name: ml-worker
    root: python-services/poloniex
    builder: RAILPACK
