nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org"
compressionLevel: 0
enableGlobalCache: false
enableStrictSettings: true
# Prevent legacy environment variable contamination
enableScripts: true