# Yarn Berry Configuration
nodeLinker: node-modules
enableGlobalCache: false
nmMode: hardlinks-local

installStatePath: .yarn/install-state.gz
enableScripts: true
enableTelemetry: false
httpTimeout: 60000
httpRetry: 3
cacheFolder: .yarn/cache