-- Migration: Autonomous Trading Agent Tables
-- Description: Creates tables for AI-powered autonomous trading agent
-- Version: 006
-- Date: 2025-01-06

-- Agent Sessions Table
-- Tracks each autonomous trading session
CREATE TABLE IF NOT EXISTS agent_sessions (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status VARCHAR(20) NOT NULL DEFAULT 'active', -- active, paused, stopped, error
  config JSONB NOT NULL DEFAULT '{}', -- agent configuration
  started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  stopped_at TIMESTAMP WITH TIME ZONE,
  last_activity_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  total_strategies_generated INTEGER NOT NULL DEFAULT 0,
  total_strategies_backtested INTEGER NOT NULL DEFAULT 0,
  total_strategies_paper_traded INTEGER NOT NULL DEFAULT 0,
  total_strategies_live INTEGER NOT NULL DEFAULT 0,
  total_profit_loss DECIMAL(20, 8) DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_agent_sessions_user_id ON agent_sessions(user_id);
CREATE INDEX idx_agent_sessions_status ON agent_sessions(status);
CREATE INDEX idx_agent_sessions_started_at ON agent_sessions(started_at DESC);

-- Agent Strategies Table
-- Stores all strategies generated by the AI agent
CREATE TABLE IF NOT EXISTS agent_strategies (
  id SERIAL PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES agent_sessions(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  strategy_name VARCHAR(255) NOT NULL,
  strategy_code TEXT NOT NULL, -- JavaScript strategy code
  strategy_params JSONB NOT NULL DEFAULT '{}', -- strategy parameters
  generation_prompt TEXT, -- prompt used to generate this strategy
  status VARCHAR(20) NOT NULL DEFAULT 'generated', -- generated, backtesting, backtest_passed, backtest_failed, paper_trading, paper_passed, paper_failed, live, retired
  backtest_score DECIMAL(10, 4), -- 0-100 score from backtesting
  backtest_results JSONB, -- detailed backtest results
  paper_trading_score DECIMAL(10, 4), -- 0-100 score from paper trading
  paper_trading_results JSONB, -- detailed paper trading results
  live_performance JSONB, -- live trading performance metrics
  promoted_to_live_at TIMESTAMP WITH TIME ZONE,
  retired_at TIMESTAMP WITH TIME ZONE,
  retirement_reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_agent_strategies_session_id ON agent_strategies(session_id);
CREATE INDEX idx_agent_strategies_user_id ON agent_strategies(user_id);
CREATE INDEX idx_agent_strategies_status ON agent_strategies(status);
CREATE INDEX idx_agent_strategies_backtest_score ON agent_strategies(backtest_score DESC);
CREATE INDEX idx_agent_strategies_created_at ON agent_strategies(created_at DESC);

-- Agent Activity Log Table
-- Logs all agent activities for monitoring and debugging
CREATE TABLE IF NOT EXISTS agent_activity_log (
  id SERIAL PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES agent_sessions(id) ON DELETE CASCADE,
  strategy_id INTEGER REFERENCES agent_strategies(id) ON DELETE SET NULL,
  activity_type VARCHAR(50) NOT NULL, -- strategy_generated, backtest_started, backtest_completed, paper_trade_started, etc.
  activity_status VARCHAR(20) NOT NULL, -- success, failure, in_progress
  message TEXT,
  details JSONB, -- additional activity details
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_agent_activity_log_session_id ON agent_activity_log(session_id);
CREATE INDEX idx_agent_activity_log_strategy_id ON agent_activity_log(strategy_id);
CREATE INDEX idx_agent_activity_log_activity_type ON agent_activity_log(activity_type);
CREATE INDEX idx_agent_activity_log_created_at ON agent_activity_log(created_at DESC);

-- Agent Learnings Table
-- Stores insights and patterns learned by the agent
CREATE TABLE IF NOT EXISTS agent_learnings (
  id SERIAL PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES agent_sessions(id) ON DELETE CASCADE,
  learning_type VARCHAR(50) NOT NULL, -- market_pattern, strategy_insight, risk_factor, optimization
  category VARCHAR(100), -- technical, fundamental, sentiment, risk_management
  insight TEXT NOT NULL, -- human-readable insight
  data JSONB, -- structured data supporting the insight
  confidence DECIMAL(5, 4) NOT NULL, -- 0-1 confidence score
  applied_count INTEGER NOT NULL DEFAULT 0, -- how many times this learning was applied
  success_rate DECIMAL(5, 4), -- success rate when applied
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_agent_learnings_session_id ON agent_learnings(session_id);
CREATE INDEX idx_agent_learnings_learning_type ON agent_learnings(learning_type);
CREATE INDEX idx_agent_learnings_confidence ON agent_learnings(confidence DESC);
CREATE INDEX idx_agent_learnings_created_at ON agent_learnings(created_at DESC);

-- Agent Performance Metrics Table
-- Tracks detailed performance metrics over time
CREATE TABLE IF NOT EXISTS agent_performance_metrics (
  id SERIAL PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES agent_sessions(id) ON DELETE CASCADE,
  metric_date DATE NOT NULL,
  total_strategies INTEGER NOT NULL DEFAULT 0,
  active_strategies INTEGER NOT NULL DEFAULT 0,
  winning_strategies INTEGER NOT NULL DEFAULT 0,
  losing_strategies INTEGER NOT NULL DEFAULT 0,
  total_trades INTEGER NOT NULL DEFAULT 0,
  winning_trades INTEGER NOT NULL DEFAULT 0,
  losing_trades INTEGER NOT NULL DEFAULT 0,
  total_profit_loss DECIMAL(20, 8) NOT NULL DEFAULT 0,
  win_rate DECIMAL(5, 4), -- 0-1
  avg_profit_per_trade DECIMAL(20, 8),
  max_drawdown DECIMAL(20, 8),
  sharpe_ratio DECIMAL(10, 4),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  UNIQUE(session_id, metric_date)
);

CREATE INDEX idx_agent_performance_metrics_session_id ON agent_performance_metrics(session_id);
CREATE INDEX idx_agent_performance_metrics_metric_date ON agent_performance_metrics(metric_date DESC);

-- Agent Market Conditions Table
-- Tracks market conditions when agent makes decisions
CREATE TABLE IF NOT EXISTS agent_market_conditions (
  id SERIAL PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES agent_sessions(id) ON DELETE CASCADE,
  symbol VARCHAR(50) NOT NULL,
  timeframe VARCHAR(10) NOT NULL,
  condition_type VARCHAR(50) NOT NULL, -- trend, volatility, volume, sentiment
  condition_value JSONB NOT NULL, -- structured condition data
  detected_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_agent_market_conditions_session_id ON agent_market_conditions(session_id);
CREATE INDEX idx_agent_market_conditions_symbol ON agent_market_conditions(symbol);
CREATE INDEX idx_agent_market_conditions_detected_at ON agent_market_conditions(detected_at DESC);

-- Update trigger for agent_sessions
CREATE OR REPLACE FUNCTION update_agent_sessions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_agent_sessions_updated_at
  BEFORE UPDATE ON agent_sessions
  FOR EACH ROW
  EXECUTE FUNCTION update_agent_sessions_updated_at();

-- Update trigger for agent_strategies
CREATE OR REPLACE FUNCTION update_agent_strategies_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_agent_strategies_updated_at
  BEFORE UPDATE ON agent_strategies
  FOR EACH ROW
  EXECUTE FUNCTION update_agent_strategies_updated_at();

-- Update trigger for agent_learnings
CREATE OR REPLACE FUNCTION update_agent_learnings_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_agent_learnings_updated_at
  BEFORE UPDATE ON agent_learnings
  FOR EACH ROW
  EXECUTE FUNCTION update_agent_learnings_updated_at();

-- Update trigger for agent_performance_metrics
CREATE OR REPLACE FUNCTION update_agent_performance_metrics_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_agent_performance_metrics_updated_at
  BEFORE UPDATE ON agent_performance_metrics
  FOR EACH ROW
  EXECUTE FUNCTION update_agent_performance_metrics_updated_at();

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON agent_sessions TO PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON agent_strategies TO PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON agent_activity_log TO PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON agent_learnings TO PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON agent_performance_metrics TO PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON agent_market_conditions TO PUBLIC;

GRANT USAGE, SELECT ON SEQUENCE agent_sessions_id_seq TO PUBLIC;
GRANT USAGE, SELECT ON SEQUENCE agent_strategies_id_seq TO PUBLIC;
GRANT USAGE, SELECT ON SEQUENCE agent_activity_log_id_seq TO PUBLIC;
GRANT USAGE, SELECT ON SEQUENCE agent_learnings_id_seq TO PUBLIC;
GRANT USAGE, SELECT ON SEQUENCE agent_performance_metrics_id_seq TO PUBLIC;
GRANT USAGE, SELECT ON SEQUENCE agent_market_conditions_id_seq TO PUBLIC;

-- Insert initial comment
COMMENT ON TABLE agent_sessions IS 'Tracks autonomous trading agent sessions';
COMMENT ON TABLE agent_strategies IS 'Stores AI-generated trading strategies';
COMMENT ON TABLE agent_activity_log IS 'Logs all agent activities';
COMMENT ON TABLE agent_learnings IS 'Stores insights learned by the agent';
COMMENT ON TABLE agent_performance_metrics IS 'Tracks agent performance over time';
COMMENT ON TABLE agent_market_conditions IS 'Records market conditions during agent decisions';
