import express from 'express';
import { authenticateToken } from '../middleware/auth.js';
import { autonomousTradingAgent } from '../services/autonomousTradingAgent.js';
import type { Request, Response } from 'express';
import { pool } from '../db/connection.js';

const router = express.Router();

/**
 * POST /api/agent/start
 * Start the autonomous trading agent
 */
router.post('/start', authenticateToken, async (req, res) => {
  try {
    const userId = req.user.id.toString();
    const config = req.body;

    const session = await autonomousTradingAgent.startAgent(userId, config);

    res.json({
      success: true,
      session
    });
  } catch (error: any) {
    console.error('Error starting agent:', error);
    res.status(500).json({
      success: false,
      error: error.message
    });
  }
});

/**
 * POST /api/agent/stop
 * Stop the autonomous trading agent
 */
router.post('/stop', authenticateToken, async (req, res) => {
  try {
    const userId = req.user.id.toString();

    // Get active session
    const status = await autonomousTradingAgent.getAgentStatus(userId);
    if (!status) {
      return res.status(404).json({
        success: false,
        error: 'No active agent session found'
      });
    }

    await autonomousTradingAgent.stopAgent(status.id);

    res.json({
      success: true,
      message: 'Agent stopped successfully'
    });
  } catch (error: any) {
    console.error('Error stopping agent:', error);
    res.status(500).json({
      success: false,
      error: error.message
    });
  }
});

/**
 * POST /api/agent/pause
 * Pause the autonomous trading agent
 */
router.post('/pause', authenticateToken, async (req, res) => {
  try {
    const userId = req.user.id.toString();

    const status = await autonomousTradingAgent.getAgentStatus(userId);
    if (!status) {
      return res.status(404).json({
        success: false,
        error: 'No active agent session found'
      });
    }

    await autonomousTradingAgent.pauseAgent(status.id);

    res.json({
      success: true,
      message: 'Agent paused successfully'
    });
  } catch (error: any) {
    console.error('Error pausing agent:', error);
    res.status(500).json({
      success: false,
      error: error.message
    });
  }
});

/**
 * GET /api/agent/status
 * Get current agent status
 */
router.get('/status', authenticateToken, async (req, res) => {
  try {
    const userId = req.user.id.toString();

    const status = await autonomousTradingAgent.getAgentStatus(userId);

    res.json({
      success: true,
      status
    });
  } catch (error: any) {
    console.error('Error getting agent status:', error);
    res.status(500).json({
      success: false,
      error: error.message
    });
  }
});

/**
 * GET /api/agent/activity
 * Get recent agent activity
 */
router.get('/activity', authenticateToken, async (req, res) => {
  try {
    const userId = req.user.id.toString();
    const limit = parseInt(req.query.limit as string) || 50;

    // Get active session
    const status = await autonomousTradingAgent.getAgentStatus(userId);
    if (!status) {
      return res.json({
        success: true,
        activity: []
      });
    }

    const result = await pool.query(
      `SELECT * FROM agent_activity_log 
       WHERE session_id = $1 
       ORDER BY created_at DESC 
       LIMIT $2`,
      [status.id, limit]
    );

    res.json({
      success: true,
      activity: result.rows
    });
  } catch (error: any) {
    console.error('Error getting agent activity:', error);
    res.status(500).json({
      success: false,
      error: error.message
    });
  }
});

/**
 * GET /api/agent/strategies
 * Get all strategies generated by the agent
 */
router.get('/strategies', authenticateToken, async (req, res) => {
  try {
    const userId = req.user.id.toString();

    const status = await autonomousTradingAgent.getAgentStatus(userId);
    if (!status) {
      return res.json({
        success: true,
        strategies: []
      });
    }

    const result = await pool.query(
      `SELECT * FROM agent_strategies 
       WHERE session_id = $1 
       ORDER BY created_at DESC`,
      [status.id]
    );

    res.json({
      success: true,
      strategies: result.rows
    });
  } catch (error: any) {
    console.error('Error getting agent strategies:', error);
    res.status(500).json({
      success: false,
      error: error.message
    });
  }
});

/**
 * GET /api/agent/performance
 * Get overall agent performance metrics
 */
router.get('/performance', authenticateToken, async (req, res) => {
  try {
    const userId = req.user.id.toString();

    const status = await autonomousTradingAgent.getAgentStatus(userId);
    if (!status) {
      return res.json({
        success: true,
        performance: null
      });
    }

    // Get strategy performance breakdown
    const strategyStats = await pool.query(
      `SELECT 
        status,
        COUNT(*) as count,
        AVG(backtest_score) as avg_backtest_score,
        AVG(paper_trading_score) as avg_paper_score
       FROM agent_strategies 
       WHERE session_id = $1 
       GROUP BY status`,
      [status.id]
    );

    res.json({
      success: true,
      performance: {
        session: status,
        strategyStats: strategyStats.rows
      }
    });
  } catch (error: any) {
    console.error('Error getting agent performance:', error);
    res.status(500).json({
      success: false,
      error: error.message
    });
  }
});

/**
 * GET /api/agent/learnings
 * Get insights learned by the agent
 */
router.get('/learnings', authenticateToken, async (req, res) => {
  try {
    const userId = req.user.id.toString();

    const status = await autonomousTradingAgent.getAgentStatus(userId);
    if (!status) {
      return res.json({
        success: true,
        learnings: []
      });
    }

    const result = await pool.query(
      `SELECT * FROM agent_learnings 
       WHERE session_id = $1 
       ORDER BY confidence DESC, created_at DESC 
       LIMIT 20`,
      [status.id]
    );

    res.json({
      success: true,
      learnings: result.rows
    });
  } catch (error: any) {
    console.error('Error getting agent learnings:', error);
    res.status(500).json({
      success: false,
      error: error.message
    });
  }
});

/**
 * PUT /api/agent/config
 * Update agent configuration
 */
router.put('/config', authenticateToken, async (req, res) => {
  try {
    const userId = req.user.id.toString();
    const newConfig = req.body;

    const status = await autonomousTradingAgent.getAgentStatus(userId);
    if (!status) {
      return res.status(404).json({
        success: false,
        error: 'No active agent session found'
      });
    }

    // Merge with existing config
    const updatedConfig = {
      ...status.config,
      ...newConfig
    };

    await pool.query(
      `UPDATE agent_sessions SET config = $1 WHERE id = $2`,
      [JSON.stringify(updatedConfig), status.id]
    );

    res.json({
      success: true,
      config: updatedConfig
    });
  } catch (error: any) {
    console.error('Error updating agent config:', error);
    res.status(500).json({
      success: false,
      error: error.message
    });
  }
});

/**
 * GET /api/agent/config
 * Get current agent configuration
 */
router.get('/config', authenticateToken, async (req, res) => {
  try {
    const userId = req.user.id.toString();

    const status = await autonomousTradingAgent.getAgentStatus(userId);
    if (!status) {
      return res.status(404).json({
        success: false,
        error: 'No active agent session found'
      });
    }

    res.json({
      success: true,
      config: status.config
    });
  } catch (error: any) {
    console.error('Error getting agent config:', error);
    res.status(500).json({
      success: false,
      error: error.message
    });
  }
});

export default router;
