# Nixpacks build plan for ML Worker (Python)
# This matches the project's existing pattern (backend/frontend also use Nixpacks).
# Railway will use this to install deps and start the service.

[phases.setup]
# Optionally pin Python version via environment (RAILWAY → Variables): PYTHON_VERSION=3.11
# Nixpacks auto-detects Python when requirements.txt is present.

[phases.install]
dependsOn = ["setup"]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn health:app --host 0.0.0.0 --port $PORT"

# Healthcheck is configured in railway.json (deploy.healthcheckPath="/health")
