name: Railway Deployment Monitor
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  check-deployments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run Railway validation
        run: yarn railway:validate
      - name: Check Backend Health (if deployed)
        continue-on-error: true
        run: |
          echo "Checking backend health endpoint..."
          curl -fsS https://polytrade-be.up.railway.app/api/health || echo "Backend health check failed or service not yet deployed"
      - name: Check Frontend Health (if deployed)
        continue-on-error: true
        run: |
          echo "Checking frontend health endpoint..."
          curl -fsS https://poloniex-trading-platform-production.up.railway.app/ || echo "Frontend health check failed or service not yet deployed"
